// This test code was generated by Claude (Anthropic).

#ifdef KERNEL_TESTS

#include <containers/kmax_heap.hpp>
#include <log/log.hpp>
#include <test/test.hpp>

namespace test_kmax_heap {

void test_default_constructor()
{
    kmax_heap<int, int> h;
    test::assert_true(h.empty(), "default constructed kmax_heap is empty");
    test::assert_eq(h.size(), 0ul, "default constructed kmax_heap has size 0");
}

void test_insert_single()
{
    kmax_heap<int, int> h;
    h.insert(5, 100);
    test::assert_eq(h.size(), 1ul, "insert increases size to 1");
    test::assert_true(!h.empty(), "insert makes heap non-empty");
    test::assert_eq(h.peak(), 100, "peak returns value of only element");
}

void test_peak_does_not_remove()
{
    kmax_heap<int, int> h;
    h.insert(1, 10);
    h.peak();
    h.peak();
    test::assert_eq(h.size(), 1ul, "peak does not change size");
    test::assert_eq(h.peak(), 10, "peak is idempotent");
}

void test_pop_single()
{
    kmax_heap<int, int> h;
    h.insert(1, 42);
    int v = h.peak();
    h.pop();
    test::assert_eq(v, 42, "peak returns value of only element before pop");
    test::assert_true(h.empty(), "pop empties single-element heap");
}

void test_pop_returns_maximum()
{
    kmax_heap<int, int> h;
    h.insert(30, 300);
    h.insert(10, 100);
    h.insert(20, 200);

    test::assert_eq(h.peak(), 300, "peak returns value with largest key after inserts");
    h.pop();
    test::assert_eq(h.peak(), 200, "peak returns next largest key's value");
    h.pop();
    test::assert_eq(h.peak(), 100, "peak returns smallest key's value last");
    h.pop();
    test::assert_true(h.empty(), "heap is empty after popping all elements");
}

void test_insert_ascending_order()
{
    kmax_heap<int, int> h;
    for (int i = 0; i < 10; i++) {
        h.insert(i, i * 10);
    }

    bool descending = true;
    int prev = 1000000;
    for (int i = 0; i < 10; i++) {
        int v = h.peak();
        h.pop();
        if (v > prev) {
            descending = false;
        }
        prev = v;
    }

    test::assert_true(descending, "inserting in ascending key order pops in descending value order");
}

void test_insert_descending_order()
{
    kmax_heap<int, int> h;
    for (int i = 9; i >= 0; i--) {
        h.insert(i, i * 10);
    }

    bool descending = true;
    int prev = 1000000;
    for (int i = 0; i < 10; i++) {
        int v = h.peak();
        h.pop();
        if (v > prev) {
            descending = false;
        }
        prev = v;
    }

    test::assert_true(descending, "inserting in descending key order still pops in descending value order");
}

void test_insert_scrambled_order()
{
    // Deterministic scrambled key order, chosen to exercise both left and
    // right subtrees during sift-down (max_heapify) rather than only ever
    // comparing against a left child.
    int keys[] = {50, 10, 90, 30, 70, 20, 60, 40, 80, 0, 55, 15, 95, 5, 65};
    kmax_heap<int, int> h;

    for (int k : keys) {
        h.insert(k, k);
    }

    test::assert_eq(h.size(), 15ul, "scrambled insert: all elements present");

    int prev = 1000000;
    bool descending = true;
    std::size_t count = 0;
    while (!h.empty()) {
        int v = h.peak();
        h.pop();
        if (v > prev) {
            descending = false;
        }
        prev = v;
        count++;
    }

    test::assert_true(descending, "scrambled insert: pop order is non-increasing");
    test::assert_eq(count, 15ul, "scrambled insert: popped every element");
}

void test_duplicate_keys()
{
    kmax_heap<int, int> h;
    h.insert(5, 1);
    h.insert(5, 2);
    h.insert(5, 3);

    test::assert_eq(h.size(), 3ul, "duplicate keys: all entries inserted");

    int sum = h.peak();
    h.pop();
    sum += h.peak();
    h.pop();
    sum += h.peak();
    h.pop();

    test::assert_eq(sum, 6, "duplicate keys: all values popped regardless of tie-breaking order");
    test::assert_true(h.empty(), "duplicate keys: heap empty after popping all");
}

void test_key_value_association()
{
    // Value is independent of key ordering, so this also checks that
    // peak/pop return the *value* tied to the largest key, not the key itself.
    kmax_heap<int, int> h;
    h.insert(1, 111);
    h.insert(3, 999);
    h.insert(2, 222);

    test::assert_eq(h.peak(), 999, "key/value association: peak returns value for largest key");
    h.pop();
    test::assert_eq(h.peak(), 222, "key/value association: peak returns value for key 2 after pop");
    h.pop();
    test::assert_eq(h.peak(), 111, "key/value association: peak returns value for key 1 after pop");
    h.pop();
}

void test_interleaved_insert_and_pop()
{
    kmax_heap<int, int> h;

    h.insert(10, 10);
    h.insert(5, 5);
    test::assert_eq(h.peak(), 10, "interleaved: first peak returns current maximum");
    h.pop();

    h.insert(20, 20);
    h.insert(1, 1);
    test::assert_eq(h.peak(), 20, "interleaved: peak after further inserts returns new maximum");
    h.pop();

    test::assert_eq(h.peak(), 5, "interleaved: next peak returns next maximum");
    h.pop();
    test::assert_eq(h.peak(), 1, "interleaved: last peak returns remaining element");
    h.pop();
    test::assert_true(h.empty(), "interleaved: heap empty after all pops");
}

void test_large_stress()
{
    // Deterministic pseudo-random-looking permutation (no rand() in kernel),
    // large enough to build a heap several levels deep and repeatedly
    // exercise max_heapify's left/right subtree comparisons on pop.
    constexpr int N = 200;
    kmax_heap<int, int> h;

    for (int i = 0; i < N; i++) {
        int key = static_cast<int>((static_cast<unsigned>(i) * 2654435761u) % 100000u);
        h.insert(key, key);
    }

    test::assert_eq(h.size(), static_cast<std::size_t>(N), "stress: all elements inserted");

    int prev = 1000000;
    bool descending = true;
    std::size_t count = 0;
    while (!h.empty()) {
        int v = h.peak();
        h.pop();
        if (v > prev) {
            descending = false;
        }
        prev = v;
        count++;
    }

    test::assert_true(descending, "stress: pop order is non-increasing across many elements");
    test::assert_eq(count, static_cast<std::size_t>(N), "stress: popped every inserted element");
}

void run()
{
    log::info("Running kmax_heap tests...");

    test_default_constructor();
    test_insert_single();
    test_peak_does_not_remove();
    test_pop_single();
    test_pop_returns_maximum();
    test_insert_ascending_order();
    test_insert_descending_order();
    test_insert_scrambled_order();
    test_duplicate_keys();
    test_key_value_association();
    test_interleaved_insert_and_pop();
    test_large_stress();
}

}

#endif // KERNEL_TESTS
