// This test code was generated by Claude (Anthropic).

#include <cstdint>
#ifdef KERNEL_TESTS

#include <arch.hpp>
#include <log/log.hpp>
#include <memory/pmm.hpp>
#include <test/test.hpp>

namespace test_pmm {

void test_alloc_frame_returns_non_null()
{
    std::uintptr_t frame = pmm::alloc_frame();
    test::assert_ne(frame, 0ULL, "alloc_frame returns non-null");
    pmm::free_frame(reinterpret_cast<std::uintptr_t>(frame));
}

void test_alloc_frame_returns_aligned()
{
    std::uintptr_t addr = pmm::alloc_frame();
    test::assert_eq(addr % 4096, 0ul, "alloc_frame returns page-aligned address");
    pmm::free_frame(addr);
}

void test_sequential_allocs_differ()
{
    auto frame1 = pmm::alloc_frame();
    auto frame2 = pmm::alloc_frame();
    test::assert_ne(frame1, frame2, "sequential allocs return different addresses");
    pmm::free_frame(frame1);
    pmm::free_frame(frame2);
}

void test_free_allows_realloc()
{
    auto frame1 = pmm::alloc_frame();
    pmm::free_frame(frame1);

    // Allocate again - should succeed (might get same or different frame)
    auto frame2 = pmm::alloc_frame();
    test::assert_ne(frame2, 0, "allocation after free succeeds");
    pmm::free_frame(frame2);
}

void test_alloc_frame_decreases_free_count()
{
    std::size_t before = pmm::get_free_frames();
    auto frame = pmm::alloc_frame();
    std::size_t after = pmm::get_free_frames();

    test::assert_eq(after, before - 1, "alloc_frame decreases free count by 1");
    pmm::free_frame(frame);
}

void test_free_frame_increases_free_count()
{
    auto frame = pmm::alloc_frame();
    std::size_t before = pmm::get_free_frames();
    pmm::free_frame(frame);
    std::size_t after = pmm::get_free_frames();

    test::assert_eq(after, before + 1, "free_frame increases free count by 1");
}

void run()
{
    log::info("Running PMM tests...");

    test_alloc_frame_returns_non_null();
    test_alloc_frame_returns_aligned();
    test_sequential_allocs_differ();
    test_free_allows_realloc();
    test_alloc_frame_decreases_free_count();
    test_free_frame_increases_free_count();
}

}

#endif // KERNEL_TESTS
